### ISSUE TITLE
Please consider extracting the CPU emulation to a separate crate

### ISSUE THREAD

**Issue by omarandlorraine** [raphamorim/LR35902#1]
Hi,

For [my own project](https://github.com/omarandlorraine/strop), I need an LR35902 emulator. It's not a Gameboy emulator, but does emulate the same CPU as a gameboy. I am considering using some code from raphamorim/LR35902.

Would you accept a pull request to extract CPU-specific logic into a separate crate? This would maybe be better for reusability. What do you think.

**Comment by raphamorim** [comment]
Hey @omarandlorraine ,

The CPU isn't complete yet but I added CPU as pub mod in 8f52237.

Then you can basically do use as in the desktop folder but targeting cpu instead of gameboy:

```rust
extern crate lr35902;

use lr35902::cpu::{Cpu, Interrupt};
```

**Comment by raphamorim** [comment]
Hope that’ll help you 👍 
Closing this issue.

**Comment by omarandlorraine** [comment]
Sure, that arrangement works well for me. Thanks for your help!

**Comment by omarandlorraine** [comment]
> The CPU isn't complete yet

Do you know what's missing?
